config/routes.rb
Rails.application.routes.draw do
  #rootパス
root 'homes#top'

# 顧客用サイトのrouting
devise_for :members, controllers: {
    registrations: 'members/registrations',
    passwords: 'members/passwords',
    sessions: 'members/sessions'}

get 'homes/top' => 'homes#top', as: 'member_top'
get 'homes/about' => 'homes#about', as: 'member_about'
resources :members, only: [:edit, :show, :update,]
  get 'members/:id/unsubscribe' => 'members#unsubscribe', as: 'member_unsubscribe'
  patch 'members/:id/unsubscribe' => 'members#unsubscribe_done', as: 'member_unsubscribe_done'
  put "/members/:id/unsubscribe" => "members#unsubscribe_done", as: 'members_unsubscribe_done'
resources :orders, only: [:index, :create, :show, :new]
  get 'orders/entry' => 'orders#entry', as: 'order_entry'
  post 'orders/check' => 'orders#check', as: 'order_check'
  get 'orders/thanks' => 'orders#thanks', as: 'order_thanks'
resources :items, only: [:index, :show] do
  get :search, on: :collection
end
resources :delivery_addresses, only: [:index, :create, :show, :edit, :update, :destroy]
resources :genres, only: [:show]

#カートアイテムを全て削除メソッドのために追加
resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
end

# 管理者用サイトのrouting
devise_scope :admins do
    devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        passwords: 'admins/passwords',
        sessions: 'admins/sessions'
    }
end

namespace :admins do
    get 'homes/top' => 'homes#top', as:'top'
    resources :members, only: [:index, :edit, :show, :update] do
      member do
        patch :toggle
      end
    end

    resources :items, only: [:index, :create, :new, :edit, :show, :update]
    resources :orders, only: [:index, :create, :show, :update]
    resources :order_items, only: [:index, :create, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    get 'search' => 'searches#search', as: 'search'
end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/item.rb
class Item < ApplicationRecord

    has_many :members, through: :cart_items

	attachment :image
	has_many :cart_items
	has_many :order_items
	belongs_to :genre

	validates :name, presence: true
	validates :introduction, length: { maximum: 200 }

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
   before_action :authenticate_admin!

  def edit
    @item = Item.find(params[:id])
  end

  def index
    @items = Item.all
    @items = Item.page(params[:page]).per(10)
    @quantity = Item.count
  end

  def new
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
    @genre =Genre.find(@item.genre_id)
  end

  def create
    @item = Item.new(item_params)
    if @item.save
       redirect_to admins_items_path(@item)
    else
       render "new"
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admins_items_path(@item.id)
    else
      render "edit"
    end
  end

  def item_params
    params.require(:item).permit(:genre_id,:name,:price,:is_status,:introduction,:image)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.where(is_status: true).page(params[:page]).per(8) # where文で販売ステータスが販売中のものだけ表示させる/ページネーションの追加/8件ごとにページ作成
    @quantity = Item.count # quantity => 総量/.count =>カウントメソッド、配列の要素の数を数えるための機能

    @genres = Genre.where(is_status: true)# ジャンルが有効のみ

  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.where(is_status: true)
  end

  # ジャンル検索機能
  def search
    @items = Item.where(genre_id: params[:format]).page(params[:page]).per(8) # パラメーターで渡ってきたジャンルidを元に、Item内のgenre_idと完全一致する商品情報を取得している。
    @quantity = Item.where(genre_id: params[:format]).count # 検索してきたジャンルの商品数をカウント
    @genres = Genre.all
    render 'index'
  end
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/items/edit.html.erb
<div class="container takasa">

  <h2 class="edit-title">商品編集</h2>

  <%= form_for @item,url: {action: "update"} do |f| %>
  <!-- 画像選択欄 -->
  <div class="row">
    <div class="col-xs-4">
      <%= attachment_image_tag @item, :image, size: "300x300",  fallback: "no_image.jpg"%><br>
      <label>Image</label>
      <%= f.attachment_field :image %>
    </div>
    <!-- 商品登録フォーム -->
    <div class="col-xs-8">
      <h4 class="edit">
        <%= f.label :"商品名" ,class: "col-xs-3" %>
        <%= f.text_field :name, class: "col-xs-8 " %>
      </h4><br>
      <h4 class="edit">
        <%= f.label :"商品説明" ,class: "col-xs-3"%>
        <%= f.text_area :introduction,size: "5x10", class: "col-xs-8",style:"margin-bottom:30px;" %>
      </h4>
      <h4 class="edit">
        <%= f.label :"ジャンル" ,class: "col-xs-3 "%>
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
        <!-- f.collection_select(プロパティ名, オブジェクトの配列, value属性の項目, 表示テキストの項目) -->
        <!-- Genre.allでジャンルのテーブル内情報を持ってきてる -->
      </h4>
      <h4 class="edit">
        <%= f.label :"税別価格" ,class: "col-xs-3"%>
        <%= f.text_field :price, class: "col-xs-5"%>円<br>
      </h4>
      <h4 class="edit">
        <%= f.label :"販売ステータス" ,class: "col-xs-3" %>
        <%= f.select :is_status, [['販売中', true], ['売切れ', false]] ,class: "col-xs-8"%>
      </h4>
      <div class="text-right"><%= f.submit :変更を保存, class: "btn btn-primary" %><div>
        <% end %>
      </div>
    </div>
  </div>

app/views/admins/items/index.html.erb
<div class="container">
   <div class="row">
    <!-- ジャンル検索サイドバー -->
    

  <div class="col-xs-9">
    <h2><i class="fas fa-cookie-bite"></i> 商品一覧<span style="font-size:20px;">（全<%= @quantity %>件）</span></h2><br>

    <div class="text-right index-new"> <!-- ボタンを丸にしたい -->
    <%= link_to new_admins_item_path do %>
      <button type="button" class="btn btn-success btn-success btn-circle btn-lg">＋</button>
    <% end %>
    </div>

    <div class=item-table>
    <table class="table table-hover">
      <thead>
        <tr class="active"> <!-- active => 色をグレーに変更 -->
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to admins_item_path(item) do %>
            <%= item.name %>
            <% end %></td>
          <td><%= "#{item.price}円" %></td>
          <td><%= item.genre.name %></td>
          <td><%= item.is_status ? '販売中' : '売切れ' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    <div>
    <%= paginate @items %>
    </div>
</div>

app/views/admins/items/new.html.erb
<div class="container">
  <div class="row row-new">

    <h2>商品新規登録</h2><br>

    <%= form_for(@item, url:admins_items_path) do |f| %>
    <!-- 画像選択欄 -->
    <div class="col-xs-4">
      <div class="item-image">
        <%= attachment_image_tag @item, :image, class: "img-square", fallback: "no_image.jpg", size:"300x300" %>
      </div><br>

      <%= f.attachment_field :image %>

    </div>

    <!-- 商品登録フォーム -->
    <div class="col-xs-8">
        <div class="new-field">
          <h4><%= f.label :商品名 ,class: "col-xs-3" %>
          <%= f.text_field :name, autofocus: true, autocomplete: "name" ,class: "col-xs-8"%></h4><br>
        </div>
        <div class="new-field">
          <h4><%= f.label :商品説明 ,class: "col-xs-3" %>
          <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction" ,class: "col-xs-8"%></h4>
        </div>
        <div class="new-field">
          <h4><%= f.label :ジャンル ,class: "col-xs-3 fix" %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name %></h4>
          <!-- f.collection_select(プロパティ名, オブジェクトの配列, value属性の項目, 表示テキストの項目) -->
          <!-- Genre.allでジャンルのテーブル内情報を持ってきてる -->

        </div>
        <div class="new-field">
          <h4><%= f.label :税抜価格 ,class: "col-xs-3 block"  %>
          <%= f.text_field :price, autofocus: true, autocomplete: "unit_price_without_tax" ,class: "col-xs-8"%></h4>
        </div><br>
        <div class="new-field">
          <h4><%= f.label :販売ステータス  ,class: "col-xs-3 fix" %>
          <%= f.select :is_status, [['販売中', true], ['売切れ', false]] %></h4>
        </div>
        <div class="text-right"><%= f.submit "新規登録" ,class: "btn btn-primary"%>

        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
  <h2>商品詳細</h2><br>
  <div class="row">
    <!-- 画像選択欄 -->
    <div class="col-xs-4">
      <%= attachment_image_tag @item, :image, size: "300x300", fallback: "no_image.jpg"%><br>
    </div>

    <!-- 商品登録フォーム -->
    <div class="col-xs-8">
      <h4 style="margin-bottom: 30px;">商品名
        <%= @item.name %>
      </h4>

      <div style="display: flex;">
        <h4 style="margin: 0 30px 30px 0;">商品説明</h4>
        <div style="overflow-wrap: break-word;　word-wrap: break-word; width: 300px;">
          <%= @item.introduction %>
        </div>
      </div>

        <h4 style="margin-bottom: 30px;">ジャンル
          <%= @item.genre.name %>
        </h4>

        <h4 style="margin-bottom: 30px;">税込価格（税抜価格）
          <%= (@item.price*1.1).floor%> (<%= @item.price%>) 円
        </h4>

        <h4 style="margin-bottom: 30px;">販売ステータス
          <%= @item.is_status ? '販売中' : '売切れ' %>
        </h4>

        <%= button_to '編集する',edit_admins_item_url, method: :get ,class: "btn btn-primary ", style: "margin-left:70%;"%>
    </div>
  </div>
</div>