config/routes.rb
Rails.application.routes.draw do
  #rootパス
root 'homes#top'

# 顧客用サイトのrouting
devise_for :members, controllers: {
    registrations: 'members/registrations',
    passwords: 'members/passwords',
    sessions: 'members/sessions'}

get 'homes/top' => 'homes#top', as: 'member_top'
get 'homes/about' => 'homes#about', as: 'member_about'
resources :members, only: [:edit, :show, :update,]
  get 'members/:id/unsubscribe' => 'members#unsubscribe', as: 'member_unsubscribe'
  patch 'members/:id/unsubscribe' => 'members#unsubscribe_done', as: 'member_unsubscribe_done'
  put "/members/:id/unsubscribe" => "members#unsubscribe_done", as: 'members_unsubscribe_done'
resources :orders, only: [:index, :create, :show, :new]
  get 'orders/entry' => 'orders#entry', as: 'order_entry'
  post 'orders/check' => 'orders#check', as: 'order_check'
  get 'orders/thanks' => 'orders#thanks', as: 'order_thanks'
resources :items, only: [:index, :show] do
  get :search, on: :collection
end
resources :delivery_addresses, only: [:index, :create, :show, :edit, :update, :destroy]
resources :genres, only: [:show]

#カートアイテムを全て削除メソッドのために追加
resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
end

# 管理者用サイトのrouting
devise_scope :admins do
    devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        passwords: 'admins/passwords',
        sessions: 'admins/sessions'
    }
end

namespace :admins do
    get 'homes/top' => 'homes#top', as:'top'
    resources :members, only: [:index, :edit, :show, :update] do
      member do
        patch :toggle
      end
    end

    resources :items, only: [:index, :create, :new, :edit, :show, :update]
    resources :orders, only: [:index, :create, :show, :update]
    resources :order_items, only: [:index, :create, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    get 'search' => 'searches#search', as: 'search'
end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/cart_item.rb
class CartItem < ApplicationRecord

belongs_to :member
belongs_to :item
validates :member_id, presence: true
validates :item_id, presence: true
validates :quantity, presence: true
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_member!
  before_action :set_cart_item, only: [:show, :update, :destroy, :edit]
  before_action :set_member


  def index
    # 会員がカートに入れた商品全て
   @cart_items = @member.cart_items.all
  end

  def create
    # こう記述することで、「current_memberに関連したCartItemクラスの新しいインスタンス」が作成可能。
    # つまり、cart_items.member_id = current_member.idが済んだ状態で生成されている。
    # buildはnewと同じ意味で、アソシエーションしながらインスタンスをnewする時に形式的に使われる。
    @cart_item = current_member.cart_items.build(cart_item_params)
    # 商品idがカートアイテムに関連した商品id、会員idがカートアイテムに関連した会員id の条件に合うデータを若い順に１つだけ取得
    @current_item = CartItem.find_by(item_id: @cart_item.item_id,member_id: @cart_item.member_id)
    # カートに同じ商品がなければ新規追加、あれば既存のデータと合算
    if @current_item.nil?
      if @cart_item.save
        flash[:success] = 'カートに商品が追加されました！'
        redirect_to cart_items_path
      else
        @carts_items = @member.cart_items.all
        render 'index'
        flash[:danger] = 'カートに商品を追加できませんでした。'
      end
    else
      # 現在のカートアイテムの個数 + ? 数字の文字列を数値オブジェクトに変換するメソッド
      @current_item.quantity += params[:quantity].to_i
      @current_item.update(cart_item_params)
      redirect_to cart_items_path
    end
  end

  def update
    if @cart_item.update(cart_item_params)
      redirect_to cart_items_path
      flash[:success] = 'カート内の商品を更新しました！'
    end
  end

  def destroy
    @cart_item.destroy
    redirect_to cart_items_path
    flash[:info] = 'カートの商品を取り消しました。'
  end

  def destroy_all
    @member.cart_items.destroy_all
    redirect_to cart_items_path
    flash[:info] = 'カートを空にしました。'
  end

  private

  def set_member
    @member = current_member
  end

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :member_id, :quantity)
  end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<%= render "layouts/flash" %>
<div class="container">
	<div class="row">
		<div class="col-xs-10">
			<br>
			<h2><i class="fas fa-cart-plus"></i>ショッピングカート</h2>
		</div>
		<!-- タイトル + 全消去メソッド -->
		<br>
		<div class="col-xs-2">
			<div><%= link_to 'カートを空にする', destroy_all_cart_items_path, method: :delete, class: 'btn btn-danger' %></div>
		</div>
	</div>
	<!-- カートの商品一覧 -->
	<h4><%= notice %></h4>
	<table class="table table-hover table-bordered">
	 <thead class="thead-light">
		<tr>
			<th style="width:300px;">商品名</th>
			<th style="width:170px;">単価（税込）</th>
			<th style="width:170px;">数量</th>
			<th style="width:170px;">小計</th>
			<th style="width:170px;"></th>
		</tr>
     </thead>

	<% sum_all = 0 %>
	<% @cart_items.each do |cart_item| %>
	<tr>
		<td>
			<%= link_to item_path(cart_item.item) do %>
			<%= attachment_image_tag(cart_item.item, :image, size: "50x50", fallback: "no_image.jpg") %>
			<% end %>
			<%= link_to item_path(cart_item.item) do %>
			<%= cart_item.item.name %>
			<% end %>
		</td>
		<td>
			<!-- 消費税込みの金額 helperに定義-->
			<%= price_include_tax(cart_item.item.price) %>
		</td>
		<td>
			<%= form_with model: cart_item, local: true do |f| %>
			<%= f.number_field :quantity, value: cart_item.quantity, min:1, max:99  %>
			<!-- 商品の数を変更するボタン -->
			<%= f.submit "変更", class: "btn btn-primary" %>
			<% end %>
		</td>
		<td>
			<%= sum_item = price_include_tax(cart_item.item.price).to_i * cart_item.quantity %>円
			<% sum_all += sum_item %>
		</td>
		<td>
			<!-- 商品を一つずつ削除するボタン -->
			<%= link_to "削除する", cart_item_path(cart_item), method: :delete, class: "btn btn-danger"%>
		</td>
	</tr>
	<% end %>
</table>
<!-- 合計金額 + 情報入力 -->
<br>
<br>
<div class="row space">
	<div class="col-lg-2 offset-lg-7 space-sm">
		<!-- 会員トップページへ -->
		<%= link_to "買い物を続ける", member_top_path, class: "btn btn-primary "%>
	</div>
		<div class="row">
			 <div class="text-right">
			<h4>合計金額：
				<input type="text"  size="8"placeholder=" <%= sum_all %> ">円
			</h4>
		     </div>
		</div>
</div>
<br>
<br>
<div class="row space">
		<div class="col text-center">
		<!-- 注文情報入力(entry)画面へ -->
		<%= link_to "情報入力に進む", new_order_path, class: "btn btn-success btn-lg" %>
	    </div>
</div>