config/routes.rb
Rails.application.routes.draw do
  #rootパス
root 'homes#top'

# 顧客用サイトのrouting
devise_for :members, controllers: {
    registrations: 'members/registrations',
    passwords: 'members/passwords',
    sessions: 'members/sessions'}

get 'homes/top' => 'homes#top', as: 'member_top'
get 'homes/about' => 'homes#about', as: 'member_about'
resources :members, only: [:edit, :show, :update,]
  get 'members/:id/unsubscribe' => 'members#unsubscribe', as: 'member_unsubscribe'
  patch 'members/:id/unsubscribe' => 'members#unsubscribe_done', as: 'member_unsubscribe_done'
  put "/members/:id/unsubscribe" => "members#unsubscribe_done", as: 'members_unsubscribe_done'
resources :orders, only: [:index, :create, :show, :new]
  get 'orders/entry' => 'orders#entry', as: 'order_entry'
  post 'orders/check' => 'orders#check', as: 'order_check'
  get 'orders/thanks' => 'orders#thanks', as: 'order_thanks'
resources :items, only: [:index, :show] do
  get :search, on: :collection
end
resources :delivery_addresses, only: [:index, :create, :show, :edit, :update, :destroy]
resources :genres, only: [:show]

#カートアイテムを全て削除メソッドのために追加
resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
end

# 管理者用サイトのrouting
devise_scope :admins do
    devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        passwords: 'admins/passwords',
        sessions: 'admins/sessions'
    }
end

namespace :admins do
    get 'homes/top' => 'homes#top', as:'top'
    resources :members, only: [:index, :edit, :show, :update] do
      member do
        patch :toggle
      end
    end

    resources :items, only: [:index, :create, :new, :edit, :show, :update]
    resources :orders, only: [:index, :create, :show, :update]
    resources :order_items, only: [:index, :create, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    get 'search' => 'searches#search', as: 'search'
end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

belongs_to :member
belongs_to :item
validates :member_id, presence: true
validates :item_id, presence: true
validates :quantity, presence: true
end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord


belongs_to :member


validates :postcode, presence: true, length: {minimum: 2, maximum: 10}
validates :address, presence: true, length: {minimum: 2, maximum: 50}
validates :name, presence: true, length: {minimum: 2, maximum: 50}

  def full_address
   self.postcode + "    " + self.address + "    " + self.name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

 has_many :items

 enum is_status: { 有効: true, 無効: false }

 validates :name, presence: true

end

app/models/item.rb
class Item < ApplicationRecord

    has_many :members, through: :cart_items

	attachment :image
	has_many :cart_items
	has_many :order_items
	belongs_to :genre

	validates :name, presence: true
	validates :introduction, length: { maximum: 200 }

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :delivery_addresses,dependent: :destroy

 has_many :cart_items,dependent: :destroy

 has_many :orders

  # バリデーション
  validates :first_name,presence: true
  validates :first_name_kana,presence: true
  validates :last_name,presence: true
  validates :last_name_kana,presence: true
  validates :postcode,presence: true
  validates :address,presence: true
  validates :phone_number,presence: true

  #退会後のユーザー（is_statusがtrue）はログインできないようにする＝＞is_statusがfalseの人だけログイン可

  def active_for_authentication?
    super && (self.is_status == false)
  end

end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :member
    has_many :order_items, dependent: :destroy
    has_many :items, :through => :order_items

	enum is_payment_method: { クレジットカード: true, 銀行振込: false }
    enum order_status: {入金待ち:0, 入金確認:1, 製作中:2, 発送準備中:3, 発送済:4}

    validates :is_payment_method , presence: true
    validates :total_price , presence: true
    validates :postage , presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord


  belongs_to :order
  belongs_to :item

 enum make_status: {着手不可:0, 製作待ち:1, 製作中:2, 製作完了:3 }

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def top
  	@genres = Genre.all # ジャンルの有効無効ステータスが有効のものだけ探す/除外検索
    @items = Item.limit(3)

   #トップ画面に行く時、adminとmemberそれぞれのトップに飛ぶ
    if admin_signed_in?
      redirect_to admins_top_path # ログイン済みのトップ画面
    else
      render 'top' # ログインしてないトップ画面
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.where(is_status: true).page(params[:page]).per(8) # where文で販売ステータスが販売中のものだけ表示させる/ページネーションの追加/8件ごとにページ作成
    @quantity = Item.count # quantity => 総量/.count =>カウントメソッド、配列の要素の数を数えるための機能

    @genres = Genre.where(is_status: true)# ジャンルが有効のみ

  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
    @genres = Genre.where(is_status: true)
  end

  # ジャンル検索機能
  def search
    @items = Item.where(genre_id: params[:format]).page(params[:page]).per(8) # パラメーターで渡ってきたジャンルidを元に、Item内のgenre_idと完全一致する商品情報を取得している。
    @quantity = Item.where(genre_id: params[:format]).count # 検索してきたジャンルの商品数をカウント
    @genres = Genre.all
    render 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

def price_include_tax(price)
	# floor→小数点以下切り捨て
  price = price * 1.10
  "#{price.floor}円"
end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
   <p class="alert alert-<%= key %>">
     <%= value %>
   </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container">
  <div class="footer-icons">
  	<span><i class="fab fa-instagram fab faa-wrench animated-hover"></i></span>
    <span><i class="fab fa-twitter faa-wrench animated-hover"></i></span>
    <span><i class="fab fa-facebook-f faa-wrench animated-hover"></i></span>
  </div>
  <h1>infomation</h1><br>
  <div class="footer-info-contents flex">
    <div class="footer-info-box">
      <h3>お問い合わせ</h3>
        <p class="info-text">
          ながのcake<br>
          TEL　：000-0000-0000 <br>
          MAIL ：000@00000000.com <br>
          営業時間：午前10:00～午後18:00 <br>
          ※年末年始、祝日は定休日となります。
        </p>
    </div>
    <div class="footer-info-box">
      <h3>アクセス</h3>
        <p class="info-text">
          〒000-0000<br>
          東京都×××××××××××××<br>
          JR長野駅東口から徒歩10分<br>
        </p>
    </div>
    <div class="footer-info-box">
      <h3>お支払い方法について</h3>
        <p class="info-text">
          お支払いは以下の方法がご利用いただけます。<br>
          ・クレジットカード決済<br>
          ・銀行振り込み<br>
          <br>
          下記のカード会社がご利用いただけます。<br>
        </p>
        <div class="card-image">
          <%= image_tag('card.jpg', style: "width: 150x; height: 70px;") %>
        </div><br>
    </div>
  </div>
  <div class="container-fluid">
    <div class="footer-under-line">
      <p>©copyright チーム炭水化物 All Rights Reserved.</p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="container-fluid">
  <nav class="navbar navbar-expand-sm bg-light">
    <!-- ロゴ画像 -->
      <%= link_to image_tag('logo.png', :size => '180x110'), '/' %>

    <!-- 各種リンク。管理者ログイン時と顧客ログイン時、非ログイン時で表示切替。 -->
      <!-- 管理者 -->
      <ul class="nav navbar-nav navbar-right">
        <!--検索窓（admin）orメッセージ（member）-->
          <% if member_signed_in? %>
            <p>ようこそ! <%= current_member.last_name %><%= current_member.first_name %>さん</p>
          <% elsif admin_signed_in? %>
            <form class="form-inline my-2 my-lg-0">
              <input type="search" class="form-control mr-sm-2" placeholder="検索..." aria-label="検索...">
              <button type="submit" class="btn btn-outline-success my-2 my-sm-0">検索 
              </button>
            </form>
          <% else %><br>
            <p>いらっしゃいませゲストさん</p>
            <p>ご注文の際は<%= link_to '会員登録', new_member_registration_path, class: 'nav-link' %>をお願いいたします<p>
          <% end %>
        <% if admin_signed_in? %>
          <div class="admin-message">管理者としてログインしています</div>
          <li class="nav-item"><%= link_to '商品一覧', admins_items_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '会員一覧', admins_members_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '注文履歴一覧', admins_orders_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ジャンル管理', admins_genres_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link' %></li>
        <!-- 会員 -->
        <% elsif member_signed_in? %>
          <li class="nav-item"><%= link_to 'About', member_about_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'マイページ', member_path(current_member.id), class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '商品一覧', items_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'カート', cart_items_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト', destroy_member_session_path, method: :delete, class: 'nav-link' %></li>
        <!-- 非ログイン -->
        <% else %>
          <li class="nav-item"><%= link_to 'About', member_about_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to '商品一覧', items_path, class: 'nav-link' %></li>
          <li class="nav-item" ><%= link_to '新規登録', new_member_registration_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', new_member_session_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- font awsome -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.0.10/font-awesome-animation.css" type="text/css" media="all" />

    <link rel="stylesheet" href="css/skippr.css">
  </head>

  <body>
    <%= flash[:notice] %>
    <%= render 'layouts/header' %>
    <script src="js/jquery.min.js"></script>
    <div class="container-fluid">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>