config/routes.rb
Rails.application.routes.draw do
  #rootパス
root 'homes#top'

# 顧客用サイトのrouting
devise_for :members, controllers: {
    registrations: 'members/registrations',
    passwords: 'members/passwords',
    sessions: 'members/sessions'}

get 'homes/top' => 'homes#top', as: 'member_top'
get 'homes/about' => 'homes#about', as: 'member_about'
resources :members, only: [:edit, :show, :update,]
  get 'members/:id/unsubscribe' => 'members#unsubscribe', as: 'member_unsubscribe'
  patch 'members/:id/unsubscribe' => 'members#unsubscribe_done', as: 'member_unsubscribe_done'
  put "/members/:id/unsubscribe" => "members#unsubscribe_done", as: 'members_unsubscribe_done'
resources :orders, only: [:index, :create, :show, :new]
  get 'orders/entry' => 'orders#entry', as: 'order_entry'
  post 'orders/check' => 'orders#check', as: 'order_check'
  get 'orders/thanks' => 'orders#thanks', as: 'order_thanks'
resources :items, only: [:index, :show] do
  get :search, on: :collection
end
resources :delivery_addresses, only: [:index, :create, :show, :edit, :update, :destroy]
resources :genres, only: [:show]

#カートアイテムを全て削除メソッドのために追加
resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
end

# 管理者用サイトのrouting
devise_scope :admins do
    devise_for :admins, controllers: {
        registrations: 'admins/registrations',
        passwords: 'admins/passwords',
        sessions: 'admins/sessions'
    }
end

namespace :admins do
    get 'homes/top' => 'homes#top', as:'top'
    resources :members, only: [:index, :edit, :show, :update] do
      member do
        patch :toggle
      end
    end

    resources :items, only: [:index, :create, :new, :edit, :show, :update]
    resources :orders, only: [:index, :create, :show, :update]
    resources :order_items, only: [:index, :create, :show, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    get 'search' => 'searches#search', as: 'search'
end

end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 has_many :delivery_addresses,dependent: :destroy

 has_many :cart_items,dependent: :destroy

 has_many :orders

  # バリデーション
  validates :first_name,presence: true
  validates :first_name_kana,presence: true
  validates :last_name,presence: true
  validates :last_name_kana,presence: true
  validates :postcode,presence: true
  validates :address,presence: true
  validates :phone_number,presence: true

  #退会後のユーザー（is_statusがtrue）はログインできないようにする＝＞is_statusがfalseの人だけログイン可

  def active_for_authentication?
    super && (self.is_status == false)
  end

end

app/controllers/admins/members_controller.rb
class Admins::MembersController < ApplicationController
  before_action :authenticate_admin!

  def index
  	@members = Member.all
  end

  def show
  	@member = Member.find(params[:id])
  end

  def edit
  	@member = Member.find(params[:id])
  end

  def update
  	@member = Member.find(params[:id])
    if @member.update(member_params)
       flash[:notice] = "会員情報が更新されました"
       redirect_to admins_member_path(@member)
    else
      flash[:notice] = "会員情報の更新ができませんでした"
      render :edit
    end
  end

  #会員ステータスの切り替え
  def toggle
  	@member = Member.find(params[:id])
  	if @member.is_status?
  		  @member.is_status = false
  	else
  		  @member.is_status = true
  	end
  	@member.save
    redirect_to edit_admins_member_path(@member)
  end

  private

  def member_params
    params.require(:member).permit(:is_status, :first_name, :first_name_kana, :last_name,:last_name_kana,:postcode,:address,:phone_number,:email)
  end

end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end


  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  #

end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    before_action :authenticate_member!
    before_action :set_member
    before_action :baria_member, only: [:edit,:update,:unsubscribe]

  def create
  end

  def edit
  end

  def show
  end

  def unsubscribe
  end

  def update
    @member = current_member
    if @member.update(member_params)
       flash[:notice] = "会員情報が更新されました"
       redirect_to member_path
    else
      flash[:notice] = "会員情報の更新ができませんでした"
      render :edit
    end
  end

  def unsubscribe_done
    @member = current_member
    #会員ステータスを退会済にする
    @member.update(is_status: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to member_top_path
  end


  private
  # @memberの値をセット
  def set_member
    @member = Member.find(params[:id])
  end

  def member_params
    params.require(:member).permit(:is_status, :first_name, :first_name_kana, :last_name,:last_name_kana,:postcode,:address,:phone_number,:email)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_member
    unless params[:id].to_i == current_member.id
      redirect_to member_path(current_member)
    end
  end


end

app/helpers/admins/members_helper.rb
module Admins::MembersHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class ="col-xs-10">
      <h2>登録情報編集</h2>
　
    <div class="row">
      <%= form_with(model: @member, local: true, class: 'container') do |f| %>

        <div class='form-group row'>
          <div class='col-lg-4'>
            <h5><%= f.label :名前 %></h5>
          </div>
          <div class='col-lg-8'>
            <span style='display: inline-block;'>
              (姓)<%= f.text_field :last_name, autofocus: true, autocomplete: 'last_name', class: 'form-control' %>
            </span>
            <span style='display: inline-block;'>
              (名)<%= f.text_field :first_name, autofocus: true, autocomplete: 'first_name', class: 'form-control' %>
            </span>
          </div>
        </div>
    
        <div class='form-group row'>
          <div class='col-lg-4'>
            <h5><%= f.label :フリガナ %></h5>
          </div>
          <div class='col-lg-8'>
            <span style='display: inline-block;'>
              (セイ)<%= f.text_field :last_name_kana, autofocus: true, autocomplete: 'last_name_kana', class: 'form-control' %>
            </span>
            <span style='display: inline-block;'>
              (メイ)<%= f.text_field :first_name_kana, autofocus: true, autocomplete: 'first_name_kana', class: 'form-control' %>
            </span>
          </div>
        </div>

        <div class='form-group row'>
          <div class='col-lg-4'>
            <h5><%= f.label :Eメール %></h5>
          </div>
          <div class='col-lg-6'>
            <%= f.text_field :email, autofocus: true, autocomplete: 'email', class: 'form-control' %>
          </div>
        </div>

        <div class='form-group row'>
          <div class='col-lg-4'>
            <h5><%= f.label :電話番号（ハイフンなし） %></h5>
          </div>
          <div class='col-lg-2'>
            <%= f.text_field :phone_number, autofocus: true, autocomplete: 'phone_number', class: 'form-control' %>
          </div>
        </div>

        <div class='form-group row'>
          <div class='col-lg-4'>
            <h5><%= f.label :郵便番号（ハイフンなし） %></h5>
          </div>
          <div class='col-lg-2'>
            <%= f.text_field :postcode, autofocus: true, autocomplete: 'postcode', class: 'form-control' %>
          </div>
        </div>

        <div class='form-group row'>
          <div class='col-lg-4'>
            <h5><%= f.label :住所 %></h5>
          </div>
          <div class='col-lg-6'>
            <%= f.text_field :address, autofocus: true, autocomplete: 'address', class: 'form-control' %>
          </div>
        </div>

        <div class="formgroup row">
          <div class="col-lg-7"></div>
          <div class="col-lg-2">
            <%= f.submit '編集内容を保存する', class:'btn btn-success' %>
          </div>
          <div class="col-lg-2">
            <%= link_to "パスワード変更", edit_member_registration_path, class: 'btn btn-warning' %>
          </div>
        </div><br>
        <div class ="row">
          <div class="col-lg-11"></div>
          <div class="col-lg-1">
            <%= link_to '退会する', member_unsubscribe_path, class:'btn btn-danger'  %>
          </div>
        </div>
      <% end %>
    </div>
</div>
</div>
<%= render 'layouts/footer' %>

app/views/members/show.html.erb
<div class="container-ms">
  <div class="row">
    <div class="col-xs-10">
      <h2><i class="fas fa-user"></i> <%= current_member.last_name %> <%= current_member.first_name %>さんの会員情報詳細</h2>

      <!-- 会員情報 -->
      <table class="table">
      <tr>
        <th><h4>氏名</h4></th>
        <td><%= current_member.last_name %> <%= current_member.first_name %></td>
      </tr>

      <tr>
        <th><h4>カナ</h4></th>
        <td><%= current_member.last_name_kana %> <%= current_member.first_name_kana %></td>
      </tr>

      <tr>
        <th><h4>郵便番号</h4></th>
        <td>〒<%= current_member.postcode %></td>
      </tr>

      <tr>
        <th><h4>住所</h4></th>
        <td><%= current_member.address %></td>
      </tr>

      <tr>
        <th><h4>電話番号</h4></th>
        <td><%= current_member.phone_number %></td>
      </tr>

      <tr>
        <th><h4>Eメール</h4></th>
        <td><%= current_member.email %></td>
      </tr>


      <!-- その他のリンク -->
      <tr>
        <th><%= link_to '配送先一覧を見る', delivery_addresses_path, class: 'btn btn-info' %></th>
        <td><%= link_to '注文履歴一覧を見る', orders_path, class: 'btn btn-success' %></td>
      </tr>
      <tr>
        <th></th>
        <td><%= link_to "会員情報を編集する", edit_member_path, class: "btn btn-danger" %></td>
      </tr>
      </table>
    </div>
  </div>
</div>
<%= render 'layouts/footer' %>

app/views/members/unsubscribe.html.erb
<div class="container" style="width:40%; margin: 50px auto";>
  <div class="row space">
    <h2>本当に退会しますか？</h2>
  </div>

  <div class="row space">
    <h4>退会すると、会員登録情報や
      <br>これまでの購入履歴が閲覧できなくなります。
      <br>退会する場合は「退会する」をクリックしてください。
    </h4>
  </div>

  <div class="row space">
    <%= link_to "退会しない",member_path(current_member),class: "btn btn-primary" %>
    <%= link_to "退会する", member_unsubscribe_done_path(current_member), method: :put, "data-confirm" => "本当に退会しますか？", class: "btn btn-danger" %>
  </div>
</div>
<%= render 'layouts/footer' %>